import "@/styles/tailwind.css";

import type { Metadata } from "next";
import type { PropsWithChildren } from "react";

export const metadata: Metadata = {
	title: "Flisk",
	description: "Generated by Next.js",
};

export default function Layout({ children }: PropsWithChildren) {
	return (
		<html lang="pt-BR">
			<body>{children}</body>
		</html>
	);
}
